version: '3.3'
services:
  mhslvl-app:
    image: php:8.0-apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 8000:80
      - 443:443
    env_file:
      - .env
  
  mhslvl-app-db:
    image: mysql:latest
    ports:
      - 3307:3306
    env_file:
      - .env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
