version: '3.3'
services:
  mhslvl-app:
    image: php:8.0-apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 8080:80
      - 443:443
    env_file:
      - .env
  
  # mhslvl-app-db:
  #   image: mysql:latest
  #   ports:
  #     - ${DB_PORT}:3306
  #   environment:
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_USER=${DB_USER}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=1
  #   volumes:
  #     - "./db:/docker-entrypoint-initdb.d"
  
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   env_file:
  #     - .env
  #   ports:
  #     - ${PHPMYADMIN_PORT}:80
  #   environment:
  #     - PMA_HOST=${DB_HOST}
  #     - PMA_PORT=${DB_PORT}